version: "1"

databases:
  - name: devClicker-db
    databaseName: devclicker_db
    user: devclicker_db_user
    plan: free
    region: oregon
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    postgresMajorVersion: "17"

services:

- type: web

  name: devclicker

  runtime: python

  repo: https://github.com/webcaique/codelab-each

  branch: server

  plan: free

  envVars:

  - key: DATABASE_URL

    sync: true

  - key: DJANGO_ALLOWED_HOST

    sync: true

  - key: DEBUG

    sync: true

  - key: SECRET_KEY

    sync: true

  region: oregon

  buildCommand: pip install -r requirements.txt

  startCommand: |

    python manage.py migrate && python manage.py collectstatic --noinput && daphne -b 0.0.0.0 -p $PORT devClicker.asgi:application

  autoDeployTrigger: commit