# Generated by Django 5.2.4 on 2025-07-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='structures',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='companies',
            name='upgrade',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
