# Generated by Django 5.2.4 on 2025-07-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_companies_structures_companies_upgrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='lsCount',
            field=models.BigIntegerField(blank=True),
        ),
    ]
