# Generated by Django 5.2.4 on 2025-07-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_alter_companies_lscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='lsCount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
