# Generated by Django 5.2.4 on 2025-07-27 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_alter_companies_lscount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companies',
            old_name='upgrade',
            new_name='upgrades',
        ),
    ]
