# Generated by Django 5.2.4 on 2025-07-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_rename_upgrade_companies_upgrades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='lsCount',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
