# Generated by Django 5.2.4 on 2025-07-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.TextField()),
                ('lsCount', models.BigIntegerField()),
            ],
        ),
    ]
